# Generated by Django 6.0.6 on 2026-06-26 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL 标识')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '仪器分类',
                'verbose_name_plural': '仪器分类',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='仪器名称')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='型号')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='序列号')),
                ('room', models.CharField(blank=True, max_length=120, verbose_name='房间')),
                ('location_detail', models.CharField(blank=True, max_length=200, verbose_name='详细位置')),
                ('image', models.ImageField(blank=True, upload_to='instruments/images/', verbose_name='图片')),
                ('status', models.CharField(choices=[('normal', '正常'), ('maintenance', '维护中'), ('disabled', '停用')], default='normal', max_length=20, verbose_name='状态')),
                ('need_booking', models.BooleanField(default=True, verbose_name='是否需要预约')),
                ('need_training', models.BooleanField(default=False, verbose_name='是否需要培训')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_instruments', to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
                ('sop_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sop_instruments', to='documents.document', verbose_name='SOP 文档')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='instruments.instrumentcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '仪器',
                'verbose_name_plural': '仪器',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('purpose', models.CharField(max_length=240, verbose_name='用途')),
                ('sample_type', models.CharField(blank=True, max_length=160, verbose_name='样品类型')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='instruments.instrument', verbose_name='仪器')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_instrument_bookings', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_bookings', to=settings.AUTH_USER_MODEL, verbose_name='预约人')),
            ],
            options={
                'verbose_name': '仪器预约',
                'verbose_name_plural': '仪器预约',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentFaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_time', models.DateTimeField(verbose_name='故障时间')),
                ('description', models.TextField(verbose_name='故障描述')),
                ('status', models.CharField(choices=[('reported', '已报修'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='reported', max_length=20, verbose_name='状态')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('result', models.TextField(blank=True, verbose_name='处理结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_instrument_faults', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_reports', to='instruments.instrument', verbose_name='仪器')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument_fault_reports', to=settings.AUTH_USER_MODEL, verbose_name='报告人')),
            ],
            options={
                'verbose_name': '仪器故障报修',
                'verbose_name_plural': '仪器故障报修',
            },
        ),
        migrations.CreateModel(
            name='InstrumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='instruments/gallery/', verbose_name='图片')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='instruments.instrument', verbose_name='仪器')),
            ],
            options={
                'verbose_name': '仪器图片',
                'verbose_name_plural': '仪器图片',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentMaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='维护日期')),
                ('maintenance_type', models.CharField(blank=True, max_length=120, verbose_name='维护类型')),
                ('description', models.TextField(verbose_name='维护说明')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='费用')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='下次维护日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='instruments.instrument', verbose_name='仪器')),
                ('maintainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument_maintenance_records', to=settings.AUTH_USER_MODEL, verbose_name='维护人')),
            ],
            options={
                'verbose_name': '仪器维护记录',
                'verbose_name_plural': '仪器维护记录',
            },
        ),
        migrations.CreateModel(
            name='InstrumentQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_image', models.ImageField(blank=True, upload_to='instruments/qrcodes/', verbose_name='二维码图片')),
                ('url', models.URLField(verbose_name='入口 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='instruments.instrument', verbose_name='仪器')),
            ],
            options={
                'verbose_name': '仪器二维码',
                'verbose_name_plural': '仪器二维码',
            },
        ),
        migrations.CreateModel(
            name='InstrumentUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_start_time', models.DateTimeField(verbose_name='实际开始时间')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('sample_count', models.PositiveIntegerField(default=0, verbose_name='样品数量')),
                ('usage_detail', models.TextField(blank=True, verbose_name='使用详情')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='是否异常')),
                ('abnormal_description', models.TextField(blank=True, verbose_name='异常说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='instruments.instrumentbooking', verbose_name='预约')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='instruments.instrument', verbose_name='仪器')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument_usage_records', to=settings.AUTH_USER_MODEL, verbose_name='使用人')),
            ],
            options={
                'verbose_name': '仪器使用记录',
                'verbose_name_plural': '仪器使用记录',
            },
        ),
        migrations.CreateModel(
            name='InstrumentTrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField(verbose_name='培训日期')),
                ('is_passed', models.BooleanField(default=False, verbose_name='是否通过')),
                ('certificate_file', models.FileField(blank=True, upload_to='instruments/training/', verbose_name='培训证明')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='instruments.instrument', verbose_name='仪器')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_instrument_trainings', to=settings.AUTH_USER_MODEL, verbose_name='培训人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_training_records', to=settings.AUTH_USER_MODEL, verbose_name='受训人')),
            ],
            options={
                'verbose_name': '仪器培训记录',
                'verbose_name_plural': '仪器培训记录',
                'unique_together': {('instrument', 'user')},
            },
        ),
    ]
