# Generated by Django 6.0.6 on 2026-06-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentusagerecord',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='instrumentusagerecord',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='instrumentusagerecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='need_booking',
        ),
        migrations.DeleteModel(
            name='InstrumentBooking',
        ),
        migrations.DeleteModel(
            name='InstrumentUsageRecord',
        ),
    ]
