# Generated by Django 6.0.7 on 2026-07-16 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_room_to_location_detail(apps, schema_editor):
    Instrument = apps.get_model('instruments', 'Instrument')
    for instrument in Instrument.objects.filter(location_detail='').exclude(room=''):
        instrument.location_detail = instrument.room
        instrument.save(update_fields=['location_detail'])


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_remove_instrumentusagerecord_booking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentimage',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='instrumentmaintenancerecord',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='instrumentmaintenancerecord',
            name='maintainer',
        ),
        migrations.RemoveField(
            model_name='instrumentqrcode',
            name='instrument',
        ),
        migrations.AlterUniqueTogether(
            name='instrumenttrainingrecord',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='instrumenttrainingrecord',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='instrumenttrainingrecord',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='instrumenttrainingrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='need_training',
        ),
        migrations.RunPython(copy_room_to_location_detail, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='instrument',
            name='room',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='sop_document',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_instruments', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='notes',
            field=models.TextField(blank=True, verbose_name='使用说明'),
        ),
        migrations.DeleteModel(
            name='InstrumentFaultReport',
        ),
        migrations.DeleteModel(
            name='InstrumentImage',
        ),
        migrations.DeleteModel(
            name='InstrumentMaintenanceRecord',
        ),
        migrations.DeleteModel(
            name='InstrumentQRCode',
        ),
        migrations.DeleteModel(
            name='InstrumentTrainingRecord',
        ),
    ]
