# Generated by Django 6.0.6 on 2026-07-01 08:17

from django.db import migrations, models


def seed_postdoc_role(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    Role.objects.update_or_create(
        code="postdoc",
        defaults={
            "name": "博士后",
            "description": "课题组博士后身份，可访问成员内部资料和科研管理信息。",
            "is_system": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_system_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('member', '课题组成员'), ('master', '硕士生'), ('phd', '博士生'), ('postdoc', '博士后'), ('instrument_manager', '仪器管理员'), ('document_manager', '资料管理员'), ('editor', '网站编辑'), ('pi', '硕博导师'), ('admin', '系统管理员')], max_length=64, unique=True, verbose_name='角色编码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role_type',
            field=models.CharField(choices=[('pending', '注册待审核用户'), ('member', '课题组成员'), ('master', '硕士生'), ('phd', '博士生'), ('postdoc', '博士后'), ('instrument_manager', '仪器管理员'), ('document_manager', '资料管理员'), ('editor', '网站编辑'), ('pi', '硕博导师'), ('admin', '系统管理员')], default='pending', max_length=32, verbose_name='主角色'),
        ),
        migrations.RunPython(seed_postdoc_role, migrations.RunPython.noop),
    ]
