# Generated by Django 6.0.6 on 2026-07-02

from django.db import migrations, models


ROLE_CHOICES = [
    ("member", "课题组成员"),
    ("master", "硕士生"),
    ("phd", "博士生"),
    ("undergraduate", "本科生"),
    ("postdoc", "博士后"),
    ("other", "其他"),
    ("instrument_manager", "仪器管理员"),
    ("document_manager", "资料管理员"),
    ("editor", "网站编辑"),
    ("pi", "硕博导师"),
    ("admin", "系统管理员"),
]

PROFILE_ROLE_CHOICES = [("pending", "注册待审核用户"), *ROLE_CHOICES]


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_role_code_alter_userprofile_role_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(choices=ROLE_CHOICES, max_length=64, unique=True, verbose_name="角色编码"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role_type",
            field=models.CharField(choices=PROFILE_ROLE_CHOICES, default="pending", max_length=32, verbose_name="主角色"),
        ),
    ]
