# Generated by Django 6.0.6 on 2026-06-26 02:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='奖励名称')),
                ('award_level', models.CharField(blank=True, max_length=120, verbose_name='奖励等级')),
                ('award_date', models.DateField(blank=True, null=True, verbose_name='获奖日期')),
                ('participants', models.TextField(blank=True, verbose_name='参与人员')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('members', '成员可见'), ('admins', '管理员可见')], default='public', max_length=20, verbose_name='可见性')),
            ],
            options={
                'verbose_name': '奖励',
                'verbose_name_plural': '奖励',
                'ordering': ['-award_date'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='著作名称')),
                ('authors', models.TextField(blank=True, verbose_name='作者')),
                ('publisher', models.CharField(blank=True, max_length=160, verbose_name='出版社')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('isbn', models.CharField(blank=True, max_length=80, verbose_name='ISBN')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('members', '成员可见'), ('admins', '管理员可见')], default='public', max_length=20, verbose_name='可见性')),
            ],
            options={
                'verbose_name': '著作',
                'verbose_name_plural': '著作',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='专利名称')),
                ('patent_number', models.CharField(blank=True, max_length=120, verbose_name='专利号')),
                ('inventors', models.TextField(blank=True, verbose_name='发明人')),
                ('application_date', models.DateField(blank=True, null=True, verbose_name='申请日期')),
                ('authorization_date', models.DateField(blank=True, null=True, verbose_name='授权日期')),
                ('status', models.CharField(blank=True, max_length=80, verbose_name='状态')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('members', '成员可见'), ('admins', '管理员可见')], default='public', max_length=20, verbose_name='可见性')),
            ],
            options={
                'verbose_name': '专利',
                'verbose_name_plural': '专利',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='项目名称')),
                ('project_number', models.CharField(blank=True, max_length=100, verbose_name='项目编号')),
                ('funding_source', models.CharField(blank=True, max_length=160, verbose_name='资助来源')),
                ('principal_investigator', models.CharField(blank=True, max_length=80, verbose_name='负责人')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='经费')),
                ('status', models.CharField(blank=True, max_length=80, verbose_name='状态')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('members', '成员可见'), ('admins', '管理员可见')], default='public', max_length=20, verbose_name='可见性')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='论文题目')),
                ('authors', models.TextField(verbose_name='作者')),
                ('journal', models.CharField(blank=True, max_length=200, verbose_name='期刊')),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='年份')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='卷')),
                ('issue', models.CharField(blank=True, max_length=50, verbose_name='期')),
                ('pages', models.CharField(blank=True, max_length=80, verbose_name='页码')),
                ('doi', models.CharField(blank=True, max_length=160, verbose_name='DOI')),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='影响因子')),
                ('jcr_partition', models.CharField(blank=True, max_length=40, verbose_name='JCR 分区')),
                ('cas_partition', models.CharField(blank=True, max_length=40, verbose_name='中科院分区')),
                ('abstract', models.TextField(blank=True, verbose_name='摘要')),
                ('pdf_file', models.FileField(blank=True, upload_to='publications/papers/', verbose_name='PDF 文件')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('members', '成员可见'), ('admins', '管理员可见')], default='public', max_length=20, verbose_name='可见性')),
                ('is_representative', models.BooleanField(default=False, verbose_name='代表性成果')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '论文',
                'verbose_name_plural': '论文',
                'ordering': ['-year', 'sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareCopyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='软著名称')),
                ('registration_number', models.CharField(blank=True, max_length=120, verbose_name='登记号')),
                ('authors', models.TextField(blank=True, verbose_name='作者')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='登记日期')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('members', '成员可见'), ('admins', '管理员可见')], default='public', max_length=20, verbose_name='可见性')),
            ],
            options={
                'verbose_name': '软件著作权',
                'verbose_name_plural': '软件著作权',
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='标准名称')),
                ('standard_number', models.CharField(blank=True, max_length=120, verbose_name='标准号')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('participants', models.TextField(blank=True, verbose_name='参与人员')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('members', '成员可见'), ('admins', '管理员可见')], default='public', max_length=20, verbose_name='可见性')),
            ],
            options={
                'verbose_name': '标准',
                'verbose_name_plural': '标准',
                'ordering': ['-publish_date'],
            },
        ),
    ]
