# Generated by Django 6.0.6 on 2026-07-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='attachment',
            field=models.FileField(blank=True, upload_to='publications/awards/files/', verbose_name='获奖附件'),
        ),
        migrations.AddField(
            model_name='award',
            name='image',
            field=models.ImageField(blank=True, upload_to='publications/awards/images/', verbose_name='获奖图片'),
        ),
        migrations.AddField(
            model_name='patent',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='publications/patents/', verbose_name='PDF 文件'),
        ),
    ]
