# Generated by Django 6.0.6 on 2026-07-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_award_attachment_award_image_patent_pdf_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['sort_order', '-award_date', 'title'], 'verbose_name': '奖励', 'verbose_name_plural': '奖励'},
        ),
        migrations.AlterModelOptions(
            name='patent',
            options={'ordering': ['sort_order', '-application_date', '-authorization_date', 'title'], 'verbose_name': '专利', 'verbose_name_plural': '专利'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['sort_order', '-start_date', 'title'], 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AddField(
            model_name='award',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='patent',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='project',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
    ]
