# Generated by Django 6.0.6 on 2026-06-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='联系我们', max_length=120, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='说明')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('map_url', models.URLField(blank=True, verbose_name='地图链接')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '联系信息',
                'verbose_name_plural': '联系信息',
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, max_length=260, verbose_name='副标题')),
                ('image', models.ImageField(blank=True, upload_to='portal/banners/', verbose_name='图片')),
                ('link', models.URLField(blank=True, verbose_name='链接')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '首页轮播',
                'verbose_name_plural': '首页轮播',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='标题')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='URL 标识')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('cover_image', models.ImageField(blank=True, upload_to='portal/research/', verbose_name='封面图')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '研究方向',
                'verbose_name_plural': '研究方向',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LabHub', max_length=120, verbose_name='站点名称')),
                ('site_subtitle', models.CharField(blank=True, max_length=200, verbose_name='站点副标题')),
                ('logo', models.ImageField(blank=True, upload_to='portal/logos/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, upload_to='portal/favicons/', verbose_name='Favicon')),
                ('description', models.TextField(blank=True, verbose_name='站点描述')),
                ('keywords', models.CharField(blank=True, max_length=300, verbose_name='关键词')),
                ('footer_text', models.TextField(blank=True, verbose_name='页脚文字')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('map_embed', models.TextField(blank=True, verbose_name='地图嵌入代码')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点设置',
                'verbose_name_plural': '站点设置',
            },
        ),
    ]
