# Generated by Django 6.0.6 on 2026-06-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='中农雨磷', max_length=120, verbose_name='站点名称'),
        ),
    ]
