# Generated by Django 6.0.6 on 2026-07-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_sitesetting_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='portal/hero/', verbose_name='首页横幅图'),
        ),
    ]
