# Generated by Django 6.0.6 on 2026-06-26 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL 标识')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '新闻分类',
                'verbose_name_plural': '新闻分类',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='标签名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL 标识')),
            ],
            options={
                'verbose_name': '新闻标签',
                'verbose_name_plural': '新闻标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL 标识')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='内容')),
                ('cover_image', models.ImageField(blank=True, upload_to='news/covers/', verbose_name='封面图')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='活动日期')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地点')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('members', '成员可见'), ('admins', '管理员可见')], default='public', max_length=20, verbose_name='可见性')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.newscategory', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='news.newstag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '新闻文章',
                'verbose_name_plural': '新闻文章',
                'ordering': ['-is_pinned', '-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/images/', verbose_name='图片')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='图片说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.newsarticle', verbose_name='文章')),
            ],
            options={
                'verbose_name': '新闻图片',
                'verbose_name_plural': '新闻图片',
                'ordering': ['sort_order'],
            },
        ),
    ]
