# Generated by Django 6.0.6 on 2026-07-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='word_file',
            field=models.FileField(blank=True, upload_to='news/word/', verbose_name='Word 新闻稿'),
        ),
    ]
