# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_prune_news_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="word_html",
            field=models.TextField(blank=True, verbose_name="Word HTML"),
        ),
    ]
