# Generated by Django 6.0.6 on 2026-06-26 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='姓名')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='英文名')),
                ('avatar', models.ImageField(blank=True, upload_to='members/avatars/', verbose_name='头像')),
                ('role_type', models.CharField(choices=[('PI', '硕博导师'), ('teacher', '教师'), ('postdoc', '博士后'), ('phd', '博士生'), ('master', '硕士生'), ('undergraduate', '本科生'), ('alumni', '已毕业学生'), ('visitor', '访问学生')], max_length=32, verbose_name='成员类型')),
                ('grade', models.CharField(blank=True, max_length=40, verbose_name='年级')),
                ('research_direction', models.CharField(blank=True, max_length=200, verbose_name='研究方向')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('profile', models.TextField(blank=True, verbose_name='个人简介')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='加入日期')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='毕业日期')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='毕业去向')),
                ('is_public', models.BooleanField(default=True, verbose_name='公开展示')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '成员',
                'verbose_name_plural': '成员',
                'ordering': ['sort_order', 'role_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MemberEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=160, verbose_name='学校')),
                ('degree', models.CharField(blank=True, max_length=80, verbose_name='学位')),
                ('major', models.CharField(blank=True, max_length=120, verbose_name='专业')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='members.member', verbose_name='成员')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MemberExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=160, verbose_name='单位')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='职位')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='members.member', verbose_name='成员')),
            ],
            options={
                'verbose_name': '工作/科研经历',
                'verbose_name_plural': '工作/科研经历',
                'ordering': ['-start_date'],
            },
        ),
    ]
