# Generated by Django 6.0.6 on 2026-06-26 02:05

import apps.documents.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seed_system_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='标签名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL 标识')),
            ],
            options={
                'verbose_name': '资料标签',
                'verbose_name_plural': '资料标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL 标识')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('members', '成员可见'), ('phd', '博士/管理员可见'), ('pi', '导师/管理员可见'), ('custom', '指定人员可见')], default='members', max_length=20, verbose_name='可见性')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentcategory', verbose_name='父级分类')),
            ],
            options={
                'verbose_name': '资料分类',
                'verbose_name_plural': '资料分类',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='资料标题')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('current_version', models.CharField(blank=True, max_length=40, verbose_name='当前版本')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('members', '成员可见'), ('phd', '博士/管理员可见'), ('pi', '导师/管理员可见'), ('custom', '指定人员可见')], default='members', max_length=20, verbose_name='可见性')),
                ('allow_download', models.BooleanField(default=True, verbose_name='允许下载')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '有效'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('maintainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_documents', to=settings.AUTH_USER_MODEL, verbose_name='维护人')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_documents', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, related_name='documents', to='documents.documenttag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '资料',
                'verbose_name_plural': '资料',
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True, verbose_name='可查看')),
                ('can_download', models.BooleanField(default=True, verbose_name='可下载')),
                ('can_edit', models.BooleanField(default=False, verbose_name='可编辑')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_permissions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='documents.document', verbose_name='资料')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to='accounts.role', verbose_name='角色')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '资料权限',
                'verbose_name_plural': '资料权限',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40, verbose_name='版本号')),
                ('file', models.FileField(storage=apps.documents.storage.ProtectedMediaStorage(), upload_to='documents/', verbose_name='文件')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('change_log', models.TextField(blank=True, verbose_name='更新说明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='文件类型')),
                ('is_current', models.BooleanField(default=True, verbose_name='是否当前版本')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='资料')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_versions', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '资料版本',
                'verbose_name_plural': '资料版本',
                'ordering': ['-uploaded_at'],
                'unique_together': {('document', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DocumentDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='下载时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='documents.document', verbose_name='资料')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_download_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_logs', to='documents.documentversion', verbose_name='版本')),
            ],
            options={
                'verbose_name': '资料下载日志',
                'verbose_name_plural': '资料下载日志',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='documents.document', verbose_name='资料')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '资料收藏',
                'verbose_name_plural': '资料收藏',
                'unique_together': {('document', 'user')},
            },
        ),
    ]
