# Generated by Django 6.0.6 on 2026-06-30 08:08

import apps.documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='preview_error',
            field=models.CharField(blank=True, max_length=240, verbose_name='预览错误'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='preview_pdf',
            field=models.FileField(blank=True, storage=apps.documents.storage.ProtectedMediaStorage(), upload_to='documents/previews/', verbose_name='PDF 预览文件'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='preview_status',
            field=models.CharField(choices=[('none', '无需转换'), ('pending', '等待生成'), ('ready', '已生成'), ('failed', '生成失败')], default='none', max_length=20, verbose_name='预览状态'),
        ),
        migrations.AlterField(
            model_name='document',
            name='visibility',
            field=models.CharField(choices=[('public', '公开'), ('members', '成员可见'), ('phd', '博士/管理员可见'), ('pi', '硕博导师/管理员可见'), ('custom', '指定人员可见')], default='members', max_length=20, verbose_name='可见性'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='visibility',
            field=models.CharField(choices=[('public', '公开'), ('members', '成员可见'), ('phd', '博士/管理员可见'), ('pi', '硕博导师/管理员可见'), ('custom', '指定人员可见')], default='members', max_length=20, verbose_name='可见性'),
        ),
    ]
