# Generated by Django 6.0.7 on 2026-07-16 10:44

import apps.documents.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_current_file_to_document(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    DocumentVersion = apps.get_model('documents', 'DocumentVersion')
    for document in Document.objects.all().iterator():
        version = (
            DocumentVersion.objects.filter(document_id=document.id, is_current=True).order_by('-uploaded_at', '-id').first()
            or DocumentVersion.objects.filter(document_id=document.id).order_by('-uploaded_at', '-id').first()
        )
        if not version:
            continue
        document.file = version.file
        document.preview_pdf = version.preview_pdf
        document.preview_status = version.preview_status
        document.preview_error = version.preview_error
        document.original_filename = version.original_filename
        document.uploaded_by_id = version.uploaded_by_id or document.owner_id
        document.uploaded_at = version.uploaded_at
        document.file_size = version.file_size
        document.file_type = version.file_type
        document.save(
            update_fields=[
                'file', 'preview_pdf', 'preview_status', 'preview_error', 'original_filename',
                'uploaded_by', 'uploaded_at', 'file_size', 'file_type',
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_refine_document_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, storage=apps.documents.storage.ProtectedMediaStorage(), upload_to='documents/', verbose_name='文件'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='文件大小'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='文件类型'),
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='原始文件名'),
        ),
        migrations.AddField(
            model_name='document',
            name='preview_error',
            field=models.CharField(blank=True, max_length=240, verbose_name='预览错误'),
        ),
        migrations.AddField(
            model_name='document',
            name='preview_pdf',
            field=models.FileField(blank=True, storage=apps.documents.storage.ProtectedMediaStorage(), upload_to='documents/previews/', verbose_name='PDF 预览文件'),
        ),
        migrations.AddField(
            model_name='document',
            name='preview_status',
            field=models.CharField(choices=[('none', '无需转换'), ('pending', '等待生成'), ('ready', '已生成'), ('failed', '生成失败')], default='none', max_length=20, verbose_name='预览状态'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上传时间'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.RunPython(copy_current_file_to_document, migrations.RunPython.noop),
        migrations.RemoveField(model_name='documentdownloadlog', name='version'),
        migrations.RemoveField(model_name='document', name='current_version'),
        migrations.RemoveField(model_name='document', name='maintainer'),
        migrations.RemoveField(model_name='document', name='visibility'),
        migrations.RemoveField(model_name='documentcategory', name='visibility'),
        migrations.DeleteModel(
            name='DocumentFavorite',
        ),
        migrations.DeleteModel(
            name='DocumentPermission',
        ),
        migrations.DeleteModel(
            name='DocumentVersion',
        ),
    ]
