# Generated by Django 6.0.6 on 2026-06-26 02:34

import apps.documents.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='姓名')),
                ('degree_type', models.CharField(choices=[('master', '硕士'), ('phd', '博士')], max_length=20, verbose_name='学位类型')),
                ('grade', models.CharField(blank=True, max_length=40, verbose_name='年级')),
                ('research_topic', models.CharField(blank=True, max_length=240, verbose_name='研究题目')),
                ('research_direction', models.CharField(blank=True, max_length=200, verbose_name='研究方向')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='入学日期')),
                ('proposal_date', models.DateField(blank=True, null=True, verbose_name='开题日期')),
                ('midterm_date', models.DateField(blank=True, null=True, verbose_name='中期日期')),
                ('pre_defense_date', models.DateField(blank=True, null=True, verbose_name='预答辩日期')),
                ('defense_date', models.DateField(blank=True, null=True, verbose_name='答辩日期')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='毕业日期')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='毕业去向')),
                ('visibility', models.CharField(choices=[('private', '本人可见'), ('supervisor', '本人/导师可见'), ('pi', '硕博导师/管理员可见'), ('members', '成员可见')], default='supervisor', max_length=20, verbose_name='可见性')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_students', to=settings.AUTH_USER_MODEL, verbose_name='导师')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学生档案',
                'verbose_name_plural': '学生档案',
                'ordering': ['-grade', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentArchiveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('proposal_report', '开题报告'), ('proposal_ppt', '开题 PPT'), ('midterm_report', '中期报告'), ('midterm_ppt', '中期 PPT'), ('pre_defense_ppt', '预答辩 PPT'), ('thesis', '毕业论文'), ('defense_ppt', '答辩 PPT'), ('raw_data_note', '原始数据说明'), ('code', '代码'), ('paper', '发表论文'), ('handover', '毕业交接材料')], max_length=40, verbose_name='文件类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('file', models.FileField(storage=apps.documents.storage.ProtectedMediaStorage(), upload_to='students/archive/', verbose_name='文件')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('version', models.CharField(default='v1.0', max_length=40, verbose_name='版本')),
                ('visibility', models.CharField(choices=[('private', '本人可见'), ('supervisor', '本人/导师可见'), ('pi', '硕博导师/管理员可见'), ('members', '成员可见')], default='supervisor', max_length=20, verbose_name='可见性')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_student_files', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_files', to='students.studentprofile', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生归档文件',
                'verbose_name_plural': '学生归档文件',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DefenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defense_type', models.CharField(max_length=80, verbose_name='答辩类型')),
                ('defense_date', models.DateField(blank=True, null=True, verbose_name='答辩日期')),
                ('location', models.CharField(blank=True, max_length=160, verbose_name='地点')),
                ('committee', models.TextField(blank=True, verbose_name='委员会')),
                ('questions', models.TextField(blank=True, verbose_name='问题记录')),
                ('result', models.CharField(blank=True, max_length=120, verbose_name='结果')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_records', to='students.studentprofile', verbose_name='学生')),
            ],
            options={
                'verbose_name': '答辩记录',
                'verbose_name_plural': '答辩记录',
                'ordering': ['-defense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThesisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=260, verbose_name='论文题目')),
                ('abstract', models.TextField(blank=True, verbose_name='摘要')),
                ('keywords', models.CharField(blank=True, max_length=260, verbose_name='关键词')),
                ('thesis_file', models.FileField(blank=True, storage=apps.documents.storage.ProtectedMediaStorage(), upload_to='students/thesis/', verbose_name='论文文件')),
                ('final_version', models.CharField(blank=True, max_length=40, verbose_name='最终版本')),
                ('defense_date', models.DateField(blank=True, null=True, verbose_name='答辩日期')),
                ('committee', models.TextField(blank=True, verbose_name='答辩委员会')),
                ('result', models.CharField(blank=True, max_length=120, verbose_name='结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_record', to='students.studentprofile', verbose_name='学生')),
            ],
            options={
                'verbose_name': '论文记录',
                'verbose_name_plural': '论文记录',
            },
        ),
        migrations.CreateModel(
            name='StudentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('proposal', '开题'), ('midterm', '中期'), ('pre_defense', '预答辩'), ('defense', '答辩'), ('graduation', '毕业')], max_length=32, verbose_name='里程碑类型')),
                ('title', models.CharField(max_length=160, verbose_name='标题')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='计划日期')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('delayed', '已延期')], default='not_started', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='students.studentprofile', verbose_name='学生')),
            ],
            options={
                'verbose_name': '培养里程碑',
                'verbose_name_plural': '培养里程碑',
                'ordering': ['student', 'milestone_type'],
                'unique_together': {('student', 'milestone_type')},
            },
        ),
    ]
