# Generated by Django 6.0.6 on 2026-06-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmilestone',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentmilestone',
            name='student',
        ),
        migrations.RemoveField(
            model_name='thesisrecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='defense_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='midterm_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='pre_defense_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='proposal_date',
        ),
        migrations.DeleteModel(
            name='DefenseRecord',
        ),
        migrations.DeleteModel(
            name='StudentMilestone',
        ),
        migrations.DeleteModel(
            name='ThesisRecord',
        ),
    ]
