# Generated by Django 6.0.6 on 2026-06-30 07:56

import apps.documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentmilestone_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentarchivefile',
            name='preview_error',
            field=models.CharField(blank=True, max_length=240, verbose_name='预览错误'),
        ),
        migrations.AddField(
            model_name='studentarchivefile',
            name='preview_pdf',
            field=models.FileField(blank=True, storage=apps.documents.storage.ProtectedMediaStorage(), upload_to='students/archive/previews/', verbose_name='PDF 预览文件'),
        ),
        migrations.AddField(
            model_name='studentarchivefile',
            name='preview_status',
            field=models.CharField(choices=[('none', '无需转换'), ('pending', '等待生成'), ('ready', '已生成'), ('failed', '生成失败')], default='none', max_length=20, verbose_name='预览状态'),
        ),
    ]
