# Generated by Django 6.0.6 on 2026-07-01 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_supervisor_to_advisors(apps, schema_editor):
    StudentProfile = apps.get_model('students', 'StudentProfile')
    through = StudentProfile.advisors.through
    rows = [
        through(studentprofile_id=student.id, user_id=student.supervisor_id)
        for student in StudentProfile.objects.exclude(supervisor_id__isnull=True)
    ]
    through.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentarchivefile_preview_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='advisors',
            field=models.ManyToManyField(blank=True, related_name='advised_students', to=settings.AUTH_USER_MODEL, verbose_name='导师'),
        ),
        migrations.RunPython(copy_supervisor_to_advisors, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentprofile',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_students', to=settings.AUTH_USER_MODEL, verbose_name='主导师'),
        ),
    ]
