# Generated by Django 6.0.6 on 2026-07-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_studentarchivefile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentarchivefile',
            name='file_type',
            field=models.CharField(choices=[('proposal_report', '开题报告'), ('proposal_ppt', '开题 PPT'), ('midterm_report', '中期报告'), ('midterm_ppt', '中期 PPT'), ('pre_defense_ppt', '预答辩 PPT'), ('thesis', '毕业论文'), ('defense_ppt', '答辩 PPT'), ('raw_data_note', '原始数据说明'), ('code', '代码与分析脚本'), ('paper', '发表论文'), ('handover', '毕业交接材料'), ('other', '其它')], max_length=40, verbose_name='文件类型'),
        ),
    ]
