# Generated by Django 6.0.6 on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_alter_studentarchivefile_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="degree_type",
            field=models.CharField(choices=[("undergraduate", "本科"), ("master", "硕士"), ("phd", "博士")], max_length=20, verbose_name="学位类型"),
        ),
    ]
