# Generated by Codex on 2026-07-03

from django.db import migrations, models


def normalize_archive_file_defaults(apps, schema_editor):
    StudentArchiveFile = apps.get_model("students", "StudentArchiveFile")
    StudentArchiveFile.objects.filter(version="v1.0").update(version="")
    StudentArchiveFile.objects.filter(visibility="supervisor").update(visibility="members")


def reverse_normalize_archive_file_defaults(apps, schema_editor):
    StudentArchiveFile = apps.get_model("students", "StudentArchiveFile")
    StudentArchiveFile.objects.filter(version="").update(version="v1.0")


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0007_alter_studentprofile_degree_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentarchivefile",
            name="version",
            field=models.CharField(blank=True, default="", max_length=40, verbose_name="版本"),
        ),
        migrations.AlterField(
            model_name="studentarchivefile",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "本人可见"),
                    ("supervisor", "本人/导师可见"),
                    ("pi", "硕博导师/管理员可见"),
                    ("members", "成员可见"),
                ],
                default="members",
                max_length=20,
                verbose_name="可见性",
            ),
        ),
        migrations.RunPython(normalize_archive_file_defaults, reverse_normalize_archive_file_defaults),
    ]
