# Generated by Codex on 2026-07-03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0008_archive_file_visibility_defaults"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentarchivefile",
            name="version",
        ),
    ]
