from .base import *  # noqa: F403

DEBUG = False

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = env("DJANGO_SECURE_COOKIES")  # noqa: F405
CSRF_COOKIE_SECURE = env("DJANGO_SECURE_COOKIES")  # noqa: F405
X_FRAME_OPTIONS = "DENY"
