# Generated by Django 6.0.7 on 2026-07-27 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='公众号名称')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='简介')),
                ('source_type', models.CharField(choices=[('rss', 'RSS'), ('json_api', '开放接口'), ('manual', '仅手动录入')], default='manual', max_length=20, verbose_name='同步方式')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='RSS 或接口地址')),
                ('api_token_env', models.CharField(blank=True, help_text='如开放接口需要 Bearer Token，请填写服务器环境变量名称，不要在此填写令牌本身。', max_length=120, verbose_name='接口令牌环境变量')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('last_sync_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步尝试')),
                ('last_sync_success_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步成功')),
                ('last_sync_error', models.TextField(blank=True, verbose_name='最后同步错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公众号',
                'verbose_name_plural': '公众号',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WechatArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='文章标题')),
                ('summary', models.TextField(blank=True, verbose_name='简短摘要')),
                ('cover_url', models.URLField(blank=True, max_length=1500, verbose_name='封面图片地址')),
                ('source_url', models.URLField(max_length=1500, verbose_name='微信原文链接')),
                ('source_guid', models.CharField(blank=True, max_length=500, verbose_name='来源文章标识')),
                ('dedupe_key', models.CharField(editable=False, max_length=64, unique=True, verbose_name='去重标识')),
                ('published_at', models.DateTimeField(verbose_name='发布时间')),
                ('is_visible', models.BooleanField(default=True, verbose_name='公开展示')),
                ('is_manual', models.BooleanField(default=False, verbose_name='手动录入')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='wechat_articles.wechataccount', verbose_name='公众号')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wechat_articles', to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
            ],
            options={
                'verbose_name': '公众号文章',
                'verbose_name_plural': '公众号文章',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['-published_at'], name='wechat_pub_at_idx'), models.Index(fields=['account', '-published_at'], name='wechat_acc_pub_idx')],
            },
        ),
    ]
